require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "Gemfile"

Rails/HasManyOrHasOneDependent:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
